# Copyright 2021 ETH Zurich and the NestForge authors.
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the arena's configuration-space figure FROM the axis definitions, so it cannot drift.

The axes already ARE module constants (``tsvc.OPT_MODES``, ``flags.COST_MODELS``/``PARALLEL_MODES``/
``REDUCED_FP_MODES``/``VECLIBS``, ``build.CODEGEN_IMPLS``). This module walks them into a Mermaid
``graph TD`` -- a lane-rooted tree, since axes are lane-dependent (codegen applies only to the DaCe
lane), so a flat product would mislead. Each lane node shows the cell count its axes contribute.

:func:`write_readme` splices the block between ``<!-- AXES:BEGIN -->``/``<!-- AXES:END -->`` in
``README.md``; a unit test regenerates and compares, so the figure can't drift by neglect.

Run ``python -m nestforge.perf.render_axes --write`` to regenerate, or ``--check`` to diff against
what's committed."""
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Tuple

from nestforge import tsvc
from nestforge.build import CODEGEN_IMPLS
from nestforge.perf import flags

BEGIN = "<!-- AXES:BEGIN -->"
END = "<!-- AXES:END -->"

#: Languages / compiler families the external lanes sweep (representative labels; the actual set comes
#: from ``discover_toolchains``).
LANGUAGES: Tuple[str, ...] = ("c", "c++", "fortran")
COMPILERS: Tuple[str, ...] = ("gcc", "clang", "nvhpc", "intel")


@dataclass
class Axis:
    """One arena axis: a name and the value labels the figure shows for it."""
    name: str
    values: Tuple[str, ...]


@dataclass
class Lane:
    """One measurement lane and the axes that apply to it (axes are lane-dependent -- see module doc)."""
    key: str
    title: str
    axes: List[Axis]

    def cells(self) -> int:
        """Cells this lane contributes = product of its axis sizes (the figure annotation)."""
        n = 1
        for ax in self.axes:
            n *= len(ax.values)
        return n


def lanes() -> List[Lane]:
    """The lane/axis spec, built from the live axis constants -- add a value to a tuple and both the
    arena and this figure change together. ``veclib``/``vectorization`` show per-device symbolic leaves
    since their concrete values are chosen per device by ``device_profile``, not fixed in the figure.

    The native lane is deliberately NOT fanned over compiler/cost-model/fp:
    ``tsvc_full.measure_native_lane`` compiles ``_native.cpp`` exactly once with base flags only -- a
    single fixed reference point, rendered as one cell."""
    return [
        Lane("native", "native original.cpp reference", [
            Axis("language", ("c++", )),
            Axis("compiler", ("«first C++ toolchain on PATH»", )),
            Axis("flags", ("«-O3 + arch tuning, vendor-default fp»", )),
        ]),
        Lane("dace-cpp", "DaCe-cpp lane (speedup denominator)", [
            Axis("codegen-impl", CODEGEN_IMPLS),
            Axis("vectorization", ("«ISA x width x strategy (per-device staged select, --vectorize)»", )),
            Axis("fp", ("strict-ieee", )),
        ]),
        Lane("nest-forge", "nest-forge external-nest sweep", [
            Axis("opt-mode", tsvc.OPT_MODES),
            Axis("language", LANGUAGES),
            Axis("parallel", flags.PARALLEL_MODES),
            Axis("compiler", COMPILERS),
            Axis("cost-model", flags.COST_MODELS),
            Axis("fp", flags.REDUCED_FP_MODES),
            Axis("veclib", ("none", "«device winner»")),
        ]),
    ]


def mermaid() -> str:
    """The Mermaid ``graph TD`` source (no code fence): Arena -> lane[cells] -> axis -> value leaves."""
    out: List[str] = ["graph TD", '  ARENA["Arena (per loop nest)"]']
    for li, lane in enumerate(lanes()):
        ln = f"L{li}"
        out.append(f'  ARENA --> {ln}["{lane.title}<br/>{lane.cells()} cells"]')
        for ai, ax in enumerate(lane.axes):
            an = f"{ln}A{ai}"
            out.append(f'  {ln} --> {an}["{ax.name}"]')
            for vi, val in enumerate(ax.values):
                out.append(f'  {an} --> {ln}A{ai}V{vi}["{val}"]')
    return "\n".join(out)


def block() -> str:
    """The full marker-bounded README block: the heading, the fenced Mermaid graph, and a one-line note."""
    return "\n".join([
        BEGIN,
        "## Configuration space",
        "",
        "_Generated by `python -m nestforge.perf.render_axes --write` from the live axis constants "
        "(`tsvc.OPT_MODES`, `flags.COST_MODELS`/`PARALLEL_MODES`/`REDUCED_FP_MODES`/`VECLIBS`, "
        "`build.CODEGEN_IMPLS`). A test regenerates and compares, so it cannot drift._",
        "",
        "```mermaid",
        mermaid(),
        "```",
        END,
    ])


def splice(readme_text: str) -> str:
    """Return ``readme_text`` with the region between the markers replaced by a fresh :func:`block`. If the
    markers are absent, insert the section just before ``## Layout`` (or append if that is missing too)."""
    fresh = block()
    if BEGIN in readme_text and END in readme_text:
        pre = readme_text[:readme_text.index(BEGIN)]
        post = readme_text[readme_text.index(END) + len(END):]
        return pre + fresh + post
    anchor = "## Layout"
    if anchor in readme_text:
        at = readme_text.index(anchor)
        return readme_text[:at] + fresh + "\n\n" + readme_text[at:]
    return readme_text.rstrip() + "\n\n" + fresh + "\n"


def readme_path() -> Path:
    """The repo README.md (two levels up from this file: nestforge/perf/ -> repo root)."""
    return Path(__file__).resolve().parent.parent.parent / "README.md"


def write_readme() -> bool:
    """Regenerate the README block in place. Returns True if the file changed."""
    path = readme_path()
    old = path.read_text()
    new = splice(old)
    if new != old:
        path.write_text(new)
    return new != old


def is_fresh() -> bool:
    """True when the committed README already contains exactly the freshly-generated block."""
    return splice(readme_path().read_text()) == readme_path().read_text()


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Generate the arena configuration-space figure in the README.")
    ap.add_argument("--write", action="store_true", help="rewrite the README block in place")
    ap.add_argument("--check", action="store_true", help="print the block; exit 1 if the README is stale")
    args = ap.parse_args(argv)
    if args.write:
        changed = write_readme()
        print("README updated." if changed else "README already current.")
        return 0
    print(block())
    if args.check and not is_fresh():
        print("\nREADME configuration-space figure is STALE -- run: python -m nestforge.perf.render_axes --write",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
